/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { MicroInteractionConfigWithExperimental } from "../../../../types/MicroInteractionConfigWithExperimental";

export const AsyncTypeRequest: core.serialization.Schema<serializers.AsyncTypeRequest.Raw, Airtop.AsyncTypeRequest> =
    core.serialization.object({
        async: AsyncConfig.optional(),
        clearInputField: core.serialization.boolean().optional(),
        clientRequestId: core.serialization.string().optional(),
        configuration: MicroInteractionConfigWithExperimental.optional(),
        costThresholdCredits: core.serialization.number().optional(),
        elementDescription: core.serialization.string().optional(),
        pressEnterKey: core.serialization.boolean().optional(),
        pressTabKey: core.serialization.boolean().optional(),
        text: core.serialization.string(),
        timeThresholdSeconds: core.serialization.number().optional(),
        waitForNavigation: core.serialization.boolean().optional(),
    });

export declare namespace AsyncTypeRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clearInputField?: boolean | null;
        clientRequestId?: string | null;
        configuration?: MicroInteractionConfigWithExperimental.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription?: string | null;
        pressEnterKey?: boolean | null;
        pressTabKey?: boolean | null;
        text: string;
        timeThresholdSeconds?: number | null;
        waitForNavigation?: boolean | null;
    }
}
