/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { MonitorConfig } from "../../../../types/MonitorConfig";

export const AsyncMonitorRequest: core.serialization.Schema<
    serializers.AsyncMonitorRequest.Raw,
    Airtop.AsyncMonitorRequest
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    condition: core.serialization.string().optional(),
    configuration: MonitorConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    selector: core.serialization.string().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace AsyncMonitorRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        condition?: string | null;
        configuration?: MonitorConfig.Raw | null;
        costThresholdCredits?: number | null;
        selector?: string | null;
        timeThresholdSeconds?: number | null;
    }
}
