/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { MicroInteractionConfig } from "../../../../types/MicroInteractionConfig";

export const AsyncHoverRequest: core.serialization.Schema<serializers.AsyncHoverRequest.Raw, Airtop.AsyncHoverRequest> =
    core.serialization.object({
        async: AsyncConfig.optional(),
        clientRequestId: core.serialization.string().optional(),
        configuration: MicroInteractionConfig.optional(),
        costThresholdCredits: core.serialization.number().optional(),
        elementDescription: core.serialization.string(),
        timeThresholdSeconds: core.serialization.number().optional(),
    });

export declare namespace AsyncHoverRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: MicroInteractionConfig.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription: string;
        timeThresholdSeconds?: number | null;
    }
}
