/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { ClickConfig } from "../../../../types/ClickConfig";

export const AsyncClickRequest: core.serialization.Schema<serializers.AsyncClickRequest.Raw, Airtop.AsyncClickRequest> =
    core.serialization.object({
        async: AsyncConfig.optional(),
        clientRequestId: core.serialization.string().optional(),
        configuration: ClickConfig.optional(),
        costThresholdCredits: core.serialization.number().optional(),
        elementDescription: core.serialization.string(),
        timeThresholdSeconds: core.serialization.number().optional(),
        waitForNavigation: core.serialization.boolean().optional(),
    });

export declare namespace AsyncClickRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: ClickConfig.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription: string;
        timeThresholdSeconds?: number | null;
        waitForNavigation?: boolean | null;
    }
}
