/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { ScreenshotRequestConfig } from "../../../../types/ScreenshotRequestConfig";

export const AsyncScreenshotRequest: core.serialization.Schema<
    serializers.AsyncScreenshotRequest.Raw,
    Airtop.AsyncScreenshotRequest
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    configuration: ScreenshotRequestConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace AsyncScreenshotRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: ScreenshotRequestConfig.Raw | null;
        costThresholdCredits?: number | null;
        timeThresholdSeconds?: number | null;
    }
}
