/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { PageQueryConfig } from "../../../../types/PageQueryConfig";

export const AsyncPromptContentRequest: core.serialization.Schema<
    serializers.AsyncPromptContentRequest.Raw,
    Airtop.AsyncPromptContentRequest
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    configuration: PageQueryConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    followPaginationLinks: core.serialization.boolean().optional(),
    prompt: core.serialization.string(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace AsyncPromptContentRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: PageQueryConfig.Raw | null;
        costThresholdCredits?: number | null;
        followPaginationLinks?: boolean | null;
        prompt: string;
        timeThresholdSeconds?: number | null;
    }
}
