/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { PaginatedExtractionConfig } from "../../../../types/PaginatedExtractionConfig";

export const AsyncPaginatedExtractionRequest: core.serialization.Schema<
    serializers.AsyncPaginatedExtractionRequest.Raw,
    Airtop.AsyncPaginatedExtractionRequest
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    configuration: PaginatedExtractionConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    prompt: core.serialization.string(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace AsyncPaginatedExtractionRequest {
    interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: PaginatedExtractionConfig.Raw | null;
        costThresholdCredits?: number | null;
        prompt: string;
        timeThresholdSeconds?: number | null;
    }
}
