/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";
import { SummaryConfig } from "../../../../types/SummaryConfig";

export const AsyncSummarizeContentRequest: core.serialization.Schema<
    serializers.AsyncSummarizeContentRequest.Raw,
    Airtop.AsyncSummarizeContentRequest
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    configuration: SummaryConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    prompt: core.serialization.string().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace AsyncSummarizeContentRequest {
    export interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        configuration?: SummaryConfig.Raw | null;
        costThresholdCredits?: number | null;
        prompt?: string | null;
        timeThresholdSeconds?: number | null;
    }
}
