/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";

export const ExtractRequest: core.serialization.Schema<serializers.ExtractRequest.Raw, Airtop.ExtractRequest> =
    core.serialization.object({
        async: AsyncConfig.optional(),
        clientRequestId: core.serialization.string().optional(),
        costThresholdCredits: core.serialization.number().optional(),
        jobId: core.serialization.string(),
        nodeHandleId: core.serialization.string().optional(),
        prompt: core.serialization.string(),
        timeThresholdSeconds: core.serialization.number().optional(),
    });

export declare namespace ExtractRequest {
    export interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        costThresholdCredits?: number | null;
        jobId: string;
        nodeHandleId?: string | null;
        prompt: string;
        timeThresholdSeconds?: number | null;
    }
}
