/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { AsyncConfig } from "../../../../types/AsyncConfig";

export const OperatorPromptV1Body: core.serialization.Schema<
    serializers.OperatorPromptV1Body.Raw,
    Airtop.OperatorPromptV1Body
> = core.serialization.object({
    async: AsyncConfig.optional(),
    clientRequestId: core.serialization.string().optional(),
    costThresholdCredits: core.serialization.number().optional(),
    prompt: core.serialization.string(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace OperatorPromptV1Body {
    export interface Raw {
        async?: AsyncConfig.Raw | null;
        clientRequestId?: string | null;
        costThresholdCredits?: number | null;
        prompt: string;
        timeThresholdSeconds?: number | null;
    }
}
