/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { MonitorConfig } from "../../../../types/MonitorConfig";

export const SessionMonitorHandlerRequestBody: core.serialization.Schema<
    serializers.SessionMonitorHandlerRequestBody.Raw,
    Airtop.SessionMonitorHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    condition: core.serialization.string(),
    configuration: MonitorConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace SessionMonitorHandlerRequestBody {
    export interface Raw {
        clientRequestId?: string | null;
        condition: string;
        configuration?: MonitorConfig.Raw | null;
        costThresholdCredits?: number | null;
        timeThresholdSeconds?: number | null;
    }
}
