/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { MicroInteractionConfig } from "../../../../types/MicroInteractionConfig";
import { ScrollByConfig } from "../../../../types/ScrollByConfig";
import { ScrollToEdgeConfig } from "../../../../types/ScrollToEdgeConfig";

export const SessionScrollHandlerRequestBody: core.serialization.Schema<
    serializers.SessionScrollHandlerRequestBody.Raw,
    Airtop.SessionScrollHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    configuration: MicroInteractionConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    scrollBy: ScrollByConfig.optional(),
    scrollToEdge: ScrollToEdgeConfig.optional(),
    scrollToElement: core.serialization.string().optional(),
    scrollWithin: core.serialization.string().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace SessionScrollHandlerRequestBody {
    export interface Raw {
        clientRequestId?: string | null;
        configuration?: MicroInteractionConfig.Raw | null;
        costThresholdCredits?: number | null;
        scrollBy?: ScrollByConfig.Raw | null;
        scrollToEdge?: ScrollToEdgeConfig.Raw | null;
        scrollToElement?: string | null;
        scrollWithin?: string | null;
        timeThresholdSeconds?: number | null;
    }
}
