/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { MicroInteractionConfigWithExperimental } from "../../../../types/MicroInteractionConfigWithExperimental";

export const SessionFileInputHandlerRequestBody: core.serialization.Schema<
    serializers.SessionFileInputHandlerRequestBody.Raw,
    Airtop.SessionFileInputHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    configuration: MicroInteractionConfigWithExperimental.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    elementDescription: core.serialization.string().optional(),
    fileId: core.serialization.string().optional(),
    fileName: core.serialization.string().optional(),
    includeHiddenElements: core.serialization.boolean().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
    waitForNavigation: core.serialization.boolean().optional(),
});

export declare namespace SessionFileInputHandlerRequestBody {
    export interface Raw {
        clientRequestId?: string | null;
        configuration?: MicroInteractionConfigWithExperimental.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription?: string | null;
        fileId?: string | null;
        fileName?: string | null;
        includeHiddenElements?: boolean | null;
        timeThresholdSeconds?: number | null;
        waitForNavigation?: boolean | null;
    }
}
