/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { ClickConfig } from "../../../../types/ClickConfig";

export const SessionTypeHandlerRequestBody: core.serialization.Schema<
    serializers.SessionTypeHandlerRequestBody.Raw,
    Airtop.SessionTypeHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    configuration: ClickConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    elementDescription: core.serialization.string().optional(),
    pressEnterKey: core.serialization.boolean().optional(),
    text: core.serialization.string(),
    timeThresholdSeconds: core.serialization.number().optional(),
    waitForNavigation: core.serialization.boolean().optional(),
});

export declare namespace SessionTypeHandlerRequestBody {
    interface Raw {
        clientRequestId?: string | null;
        configuration?: ClickConfig.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription?: string | null;
        pressEnterKey?: boolean | null;
        text: string;
        timeThresholdSeconds?: number | null;
        waitForNavigation?: boolean | null;
    }
}
