/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { PaginatedExtractionConfig } from "../../../../types/PaginatedExtractionConfig";

export const SessionPaginatedExtractionHandlerRequestBody: core.serialization.Schema<
    serializers.SessionPaginatedExtractionHandlerRequestBody.Raw,
    Airtop.SessionPaginatedExtractionHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    configuration: PaginatedExtractionConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    prompt: core.serialization.string(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace SessionPaginatedExtractionHandlerRequestBody {
    interface Raw {
        clientRequestId?: string | null;
        configuration?: PaginatedExtractionConfig.Raw | null;
        costThresholdCredits?: number | null;
        prompt: string;
        timeThresholdSeconds?: number | null;
    }
}
