/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { ClickConfig } from "../../../../types/ClickConfig";

export const SessionHoverHandlerRequestBody: core.serialization.Schema<
    serializers.SessionHoverHandlerRequestBody.Raw,
    Airtop.SessionHoverHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    configuration: ClickConfig.optional(),
    costThresholdCredits: core.serialization.number().optional(),
    elementDescription: core.serialization.string().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace SessionHoverHandlerRequestBody {
    interface Raw {
        clientRequestId?: string | null;
        configuration?: ClickConfig.Raw | null;
        costThresholdCredits?: number | null;
        elementDescription?: string | null;
        timeThresholdSeconds?: number | null;
    }
}
