/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";

export const SessionSummaryHandlerRequestBody: core.serialization.Schema<
    serializers.SessionSummaryHandlerRequestBody.Raw,
    Airtop.SessionSummaryHandlerRequestBody
> = core.serialization.object({
    clientRequestId: core.serialization.string().optional(),
    costThresholdCredits: core.serialization.number().optional(),
    prompt: core.serialization.string().optional(),
    timeThresholdSeconds: core.serialization.number().optional(),
});

export declare namespace SessionSummaryHandlerRequestBody {
    interface Raw {
        clientRequestId?: string | null;
        costThresholdCredits?: number | null;
        prompt?: string | null;
        timeThresholdSeconds?: number | null;
    }
}
