/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";

export const UpdateAutomationDescriptionInputBody: core.serialization.Schema<
    serializers.UpdateAutomationDescriptionInputBody.Raw,
    Airtop.UpdateAutomationDescriptionInputBody
> = core.serialization.object({
    description: core.serialization.string(),
    id: core.serialization.string(),
    orgId: core.serialization.string(),
});

export declare namespace UpdateAutomationDescriptionInputBody {
    export interface Raw {
        description: string;
        id: string;
        orgId: string;
    }
}
