/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "^Acme.*"
 *     }
 */
export interface ProfilesDeleteRequest {
    /**
     * Name to search for, supports regex, case insensitive
     */
    name?: string;
    /**
     * a comma separated list of tags to filter by (joined by OR, e.g. tag is red OR blue)
     */
    tags?: string | string[];
}
