/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ProfilesGetRequest {
    /**
     * A comma separated list of profile ids to search for
     */
    profileIds?: string | string[];
}
