/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../../../../index";

/**
 * @example
 *     {
 *         fileName: "fileName"
 *     }
 */
export interface CreateFileRestInputV1 {
    /** Name of the file */
    fileName: string;
    /** Type of the file */
    fileType?: Airtop.CreateFileRestInputV1FileType;
    /** ID of the session */
    sessionId?: string;
}
