/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Special Widget"
 *     }
 */
export interface ExtensionsPostRequest {
    /** Name of the extension */
    name: string;
}
