/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Widget"
 *     }
 */
export interface ExtensionsGetRequest {
    /**
     * Name to search for, supports regex, case insensitive
     */
    name?: string;
}
