/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateFileRestInputV1FileType } from "../../types/CreateFileRestInputV1FileType";

export const CreateFileRestInputV1: core.serialization.Schema<
    serializers.CreateFileRestInputV1.Raw,
    Airtop.CreateFileRestInputV1
> = core.serialization.object({
    fileName: core.serialization.string(),
    fileType: CreateFileRestInputV1FileType.optional(),
    sessionId: core.serialization.string().optional(),
    sessionIds: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace CreateFileRestInputV1 {
    export interface Raw {
        fileName: string;
        fileType?: CreateFileRestInputV1FileType.Raw | null;
        sessionId?: string | null;
        sessionIds?: string[] | null;
    }
}
