/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";
import { SessionConfigV1 } from "../../../../types/SessionConfigV1";

export const SessionRestInputV1: core.serialization.Schema<
    serializers.SessionRestInputV1.Raw,
    Airtop.SessionRestInputV1
> = core.serialization.object({
    configuration: SessionConfigV1.optional(),
});

export declare namespace SessionRestInputV1 {
    export interface Raw {
        configuration?: SessionConfigV1.Raw | null;
    }
}
