/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         browserId: "7334da2a-91b0-42c5-6156-76a5eba87430",
 *         targetId: "123456"
 *     }
 */
export interface CreateLiveViewUrlRequest {
    /**
     * id of the browser to create a url for
     */
    browserId?: string;
    /**
     * id of the target to create a url for
     */
    targetId?: string;
}
