/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionsEventsRequest {
    /**
     * last known event id
     */
    lastEventId?: number;
    /**
     * Get all events
     */
    all?: boolean;
}
