/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SessionRestInputV1 {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** Session configuration */
    configuration?: Airtop.SessionConfigV1;
}
