/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AsyncConfig {
    /** The URL to send the response to when the request is complete. */
    webhookUrl?: string;
}
