/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface AsyncSessionAiResponseEnvelope {
    errors?: Airtop.Issue[];
    requestId: string;
    warnings?: Airtop.Issue[];
}
