/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AutomationOutput {
    description?: string;
    domainName: string;
    id: string;
    schema?: string;
    template?: string;
}
