/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface BrowserWaitNavigationConfig {
    /** The maximum time to wait for the navigation to complete, in seconds. Defaults to 30 (30 seconds). */
    timeoutSeconds?: number;
    /** The condition to wait for the navigation to complete. Defaults to 'load'. */
    waitUntil?: Airtop.BrowserWaitNavigationConfigWaitUntil;
}
