/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * CAPTCHA solving status
 */
export type CaptchaEventMessageStatus = "processing" | "completed" | "failed";
export const CaptchaEventMessageStatus = {
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
} as const;
