/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface CleanScrapeResponseOutput {
    /** The scraped content of the browser window */
    scrapedContent: Airtop.ScrapeResponseContent;
    /** Any text that was highlighted in the browser window */
    selectedText: string;
    /** The title of the browser page */
    title: string;
}
