/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface CleanScrapeResponse {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** The data about the scraped browser window */
    data: Airtop.CleanScrapeResponseData;
    /** Metadata about the response */
    meta: Airtop.SessionAiResponseMetadata;
}
