/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface CleanScrapeResponseData {
    /** The response to the question about this specific browser window */
    output: Airtop.CleanScrapeResponseOutput;
    /** Whether the prompt was successful */
    success: boolean;
}
