/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ConnectionInfo {
    /** Url to connect to chrome devtools protocol port on the airtop browser. Include the header 'x-airtop-token: <api-key>.' */
    cdpUrl?: string;
    /** Websocket url to connect to CDP webSocketDebuggerUrl on the airtop browser. Include the header 'x-airtop-token: <api-key>.' */
    cdpWsUrl?: string;
    /** Websocket url to connect to the chromedriver on the airtop browser. Include the header 'x-airtop-token: <api-key>.' */
    chromedriverUrl?: string;
    /** Connection info for the live view */
    liveView?: Airtop.LiveViewConnectionInfo;
}
