/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the file
 */
export type CreateFileV1FileType = "browser_download" | "screenshot" | "video" | "customer_upload";

export const CreateFileV1FileType = {
    BrowserDownload: "browser_download",
    Screenshot: "screenshot",
    Video: "video",
    CustomerUpload: "customer_upload",
} as const;
