/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface CreateFileV1 {
    /** Size of the file in bytes */
    fileBytes: number;
    /** Name of the file */
    fileName: string;
    /** Type of the file */
    fileType: Airtop.CreateFileV1FileType;
    /** ID of the file */
    id: string;
    /** ID of the organization */
    orgId: string;
    /** ID of the session */
    sessionId?: string;
    /** URL to upload the file */
    uploadUrl: string;
    /** Time when the file was uploaded */
    uploadedAt: Date;
}
