/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface EmptyResponse {
    data: Airtop.EmptyResponseJson;
    errors?: Airtop.Issue[];
    meta: Airtop.EnvelopeStatusDefaultMeta;
    warnings?: Airtop.Issue[];
}
