/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface EnvelopeCreateFileV1EnvelopeDefaultMeta {
    data: Airtop.CreateFileV1;
    errors?: Airtop.Issue[];
    meta: Airtop.EnvelopeDefaultMeta;
    warnings?: Airtop.Issue[];
}
