/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface EnvelopeExtensionV1EnvelopeDefaultMeta {
    data: Airtop.ExtensionV1;
    errors?: Airtop.Issue[];
    meta: Airtop.EnvelopeDefaultMeta;
    warnings?: Airtop.Issue[];
}
