/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface EnvelopeGetFileV1EnvelopeDefaultMeta {
    data: Airtop.GetFileV1;
    errors?: Airtop.Issue[];
    meta: Airtop.EnvelopeDefaultMeta;
    warnings?: Airtop.Issue[];
}
