/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorMessage {
    /** Error code */
    code: string;
    /** Event name */
    event: string;
    /** Error message */
    message: string;
}
