/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ErrorEnvelope {
    httpStatus: number;
    message: string;
    data?: unknown;
    errors?: Airtop.Issue[];
    meta?: unknown;
    warnings?: Airtop.Issue[];
}
