/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExternalSessionAiResponseMetadataStatus = "success" | "partial" | "failure";

export const ExternalSessionAiResponseMetadataStatus = {
    Success: "success",
    Partial: "partial",
    Failure: "failure",
} as const;
