/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExtensionConfigurationOutput {
    /** The date and time the configuration was created. Might be null for old configurations */
    createdAt?: Date;
    /** The ids of the extensions in configuration. */
    extensionIds?: string[];
    /** Name of the extension configuration. */
    name: string;
    /** The date and time the configuration was last updated. Might be null for configurations not updated recently */
    updatedAt?: Date;
}
