/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExternalFile {
    /** Whether the file has been deleted */
    deleted: boolean;
    /** Time when the file was deleted */
    deletionTime?: Date;
    /** Size of the file in bytes */
    fileBytes: number;
    /** Name of the file */
    fileName: string;
    /** Type of the file */
    fileType: string;
    /** ID of the file */
    id: string;
    /** Time when the file was last heartbeated */
    lastHeartbeatTime?: Date;
    /** ID of the organization */
    orgId: string;
    /** IDs of the associated sessions */
    sessionIds?: string[];
    /** Status of the file */
    status: string;
    /** Time when the file was uploaded */
    uploadCompleteTime?: Date;
    /** Time when the file was uploaded */
    uploadStartTime: Date;
    /** Whether the file is visible in the API */
    visibleInApi: boolean;
    /** Whether the file is visible in the portal */
    visibleInPortal: boolean;
}
