/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExternalProfileV1 {
    /** DEPRECATED. Use profileName. */
    profileId: string;
    /** Name of the profile. */
    profileName: string;
    /** DEPRECATED. */
    status?: string;
}
