/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ExternalSessionAiResponseMetadata {
    clientProvided?: Airtop.ClientProvidedResponseMetadata;
    requestId?: string;
    status: Airtop.ExternalSessionAiResponseMetadataStatus;
    usage: Airtop.ExternalSessionAiResponseMetadataUsage;
}
