/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface FileEventMessage {
    /** Download URL */
    downloadUrl: string;
    /** Event name */
    event: string;
    eventData?: unknown;
    /** Date and Time of the event */
    eventTime: Date;
    /** File ID */
    fileId: string;
    /** Status of the file */
    status: Airtop.FileEventMessageStatus;
}
