/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the file
 */
export type GetFileV1FileType = "browser_download" | "screenshot" | "recording" | "customer_upload";
export const GetFileV1FileType = {
    BrowserDownload: "browser_download",
    Screenshot: "screenshot",
    Recording: "recording",
    CustomerUpload: "customer_upload",
} as const;
