/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface GetFileV1 {
    /** URL to download the file */
    downloadUrl: string;
    /** Size of the file in bytes */
    fileBytes: number;
    /** Name of the file */
    fileName: string;
    /** Type of the file */
    fileType: Airtop.GetFileV1FileType;
    /** ID of the file */
    id: string;
    /** ID of the organization */
    orgId: string;
    /** DEPRECATED: Use sessionIds instead */
    sessionId?: string;
    /** IDs of the associated sessions */
    sessionIds?: string[];
    /** Time when the file upload was started */
    uploadStartTime: Date;
}
