/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the file
 */
export type GetFileV1Status = "available" | "uploading" | "upload_failed" | "deleted";
export const GetFileV1Status = {
    Available: "available",
    Uploading: "uploading",
    UploadFailed: "upload_failed",
    Deleted: "deleted",
} as const;
