/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IntervalMonitorConfig {
    /** The interval in seconds between condition checks. Defaults to 5 seconds. */
    intervalSeconds?: number;
    /** The timeout in seconds after which the monitor will stop checking the condition. Defaults to 30 seconds. */
    timeoutSeconds?: number;
}
