/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ListSessionWithConnectionInfoEnvelopeDefaultMetaWrapper {
    data?: Airtop.SessionWithConnectionInfo[];
    errors?: Airtop.Issue[];
    meta: Airtop.DefaultMetaWrapper;
    warnings?: Airtop.Issue[];
}
