/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LiveViewConnectionInfo {
    /** Websocket url to connect to the airtop browser */
    airtopBrowserUrl: string;
    /** Token to connect to the airtop browser, use as a header: 'Authorization: Bearer <token>' */
    token?: string;
}
