/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LiveViewUrlOutputV1Body {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** Browser ID for live view session */
    browserId: string;
    /** Token for authenticating to a live view session */
    token: string;
    /** Url for live view session */
    url: string;
}
