/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface MicroInteractionConfig {
    /** Optional configuration for visual analysis when locating specified content. */
    visualAnalysis?: Airtop.VisualAnalysisConfig;
    /** Optional configuration for waiting for navigation to complete after clicking the element. */
    waitForNavigationConfig?: Airtop.BrowserWaitNavigationConfig;
}
