/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ModelResponseExternalSessionAiResponseMetadataWrapper {
    data: Airtop.ModelResponse;
    errors?: Airtop.Issue[];
    meta: Airtop.ExternalSessionAiResponseMetadata;
    warnings?: Airtop.Issue[];
}
