/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of monitoring to perform. Interval executes the condition check at a regular, specified interval. Selector waits for a selector to be present before completing.
 */
export type MonitorConfigMonitorType = "interval" | "selector";

export const MonitorConfigMonitorType = {
    Interval: "interval",
    Selector: "selector",
} as const;
