/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If set to 'enabled', Airtop AI will also analyze the web page visually when executing the condition check. If set to 'disabled', no visual analysis will be conducted.
 */
export type MonitorConfigIncludeVisualAnalysis = "auto" | "disabled" | "enabled";
export const MonitorConfigIncludeVisualAnalysis = {
    Auto: "auto",
    Disabled: "disabled",
    Enabled: "enabled",
} as const;
