/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface MonitorConfig {
    /** If set to 'enabled', Airtop AI will also analyze the web page visually when executing the condition check. If set to 'disabled', no visual analysis will be conducted. */
    includeVisualAnalysis?: Airtop.MonitorConfigIncludeVisualAnalysis;
    /** Configuration for the interval monitor. */
    interval?: Airtop.IntervalMonitorConfig;
}
