/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PageQueryConfig {
    /** JSON schema defining the structure of the output. If not provided, the format of the output might vary. */
    outputSchema?: string;
}
