/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PageQueryExperimentalConfig {
    /** If set to 'enabled', Airtop AI will also analyze the web page visually when fulfilling the request. Note that this can add to both the execution time and cost of the operation. If the page is too large, the context window can be exceeded and the request will fail. If set to 'auto' or 'disabled', no visual analysis will be conducted. If 'followPaginationLinks' is set to true, visual analysis will be conducted unless 'includeVisualAnalysis' is explicitly set to 'disabled'. */
    includeVisualAnalysis?: string;
}
