/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface PageQueryConfig {
    /** Experimental configuration options. These may be subject to change and are not guaranteed to be stable across versions. */
    experimental?: Airtop.PageQueryExperimentalConfig;
    /** JSON schema defining the structure of the output. If not provided, the format of the output might vary. */
    outputSchema?: string;
}
