/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaginatedExtractionExperimentalConfig {
    /** A natural language description of the scrollable area on the web page. This identifies the container or region that should be scrolled to access pagination controls. If missing, the entire page will be scrolled. You can also describe a visible reference point inside the container. */
    scrollWithin?: string;
}
