/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaginatedExtractionConfig {
    /** The mode to use for interaction. If set to 'auto', Airtop AI will automatically choose the most cost-effective interaction mode. If set to 'accurate', Airtop AI will use the most accurate interaction mode. If set to 'cost-efficient', Airtop AI will use the most cost-effective interaction mode. */
    interactionMode?: string;
    /** JSON schema defining the structure of the output. If not provided, the format of the output might vary. */
    outputSchema?: string;
    /** The mode to use for pagination. If set to 'auto', Airtop AI will automatically look for pagination links first and then attempt infinite scrolling to load more content. If set to 'paginated', Airtop AI will follow pagination links to load more content. If set to 'infinite-scroll', Airtop AI will scroll the page to load more content. */
    paginationMode?: string;
}
