/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface PaginatedExtractionConfig {
    /** The mode to use for interaction. If set to 'auto', Airtop AI will automatically choose the most cost-effective interaction mode. If set to 'accurate', the request might be slower, but more likely to be accurate. Whereas, 'cost-efficient' will be cheaper and speed things up, but may reduce accuracy. */
    interactionMode?: string;
    /** JSON schema defining the structure of the output. If not provided, the format of the output might vary. */
    outputSchema?: string;
    /** The mode to use for pagination. If set to 'auto', Airtop AI will automatically look for pagination links first and then attempt infinite scrolling to load more content. If set to 'paginated', Airtop AI will follow pagination links to load more content. If set to 'infinite-scroll', Airtop AI will scroll the page to load more content. */
    paginationMode?: string;
    /** Optional configuration to customize and tweak how the web page is scraped. */
    scrape?: Airtop.ScrapeConfig;
}
