/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Pagination {
    currentLimit: number;
    currentPage: number;
    finalCount: number;
    hasMore: boolean;
    initialCount: number;
    nextOffset: number;
    numberOfPages: number;
    totalItems: number;
}
