/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ProfileV1 {
    /** Name of the profile */
    name: string;
    /** Status of the profile */
    status?: string;
    /** a comma separated list of tags for this profile */
    tags?: string[];
    /** URI to upload profile data to */
    uploadUri?: string;
}
