/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ProfileV1EnvelopeDefaultMetaWrapper {
    data: Airtop.ProfileV1;
    errors?: Airtop.Issue[];
    meta: Airtop.DefaultMetaWrapper;
    warnings?: Airtop.Issue[];
}
