/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ProfileOutputV1Body {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** created Profile */
    profile: Airtop.ProfileV1;
}
