/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Proxy object with url of the proxy as a parameter. Takes optional username and password.
 */
export interface ProxyCredentials {
    password?: string;
    url: string;
    username?: string;
}
