/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ProxyConfigurationKind {
    domainPattern: string;
    /** Configuration for a single custom proxy. */
    relay: Airtop.Proxy;
}
