/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RequestStatusResponse {
    /** The error message, if available */
    error?: string;
    response?: unknown;
    /** The current status of the request (pending, completed, error) */
    status: string;
}
