/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ScrapeResponseEnvelopeExternalSessionAiResponseMetadataWrapper {
    data: Airtop.ScrapeResponseEnvelope;
    errors?: Airtop.Issue[];
    meta: Airtop.ExternalSessionAiResponseMetadata;
    warnings?: Airtop.Issue[];
}
