/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ScrapeResponseEnvelope {
    errors?: Airtop.Issue[];
    modelResponse: Airtop.ScrapeResponseOutput;
    warnings?: Airtop.Issue[];
}
