/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScrapeResponseContent {
    /** The mime type of content extracted from the browser window */
    contentType: string;
    /** The text content of the browser window */
    text: string;
}
