/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScreenshotViewportDimensions {
    /** Height of the viewport in pixels */
    height: number;
    /** Width of the viewport in pixels */
    width: number;
}
