/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface ScreenshotMetadata {
    /** Base64 encoded data URL of screenshot image data */
    dataUrl?: string;
    /** Unique identifier for the uploaded file */
    fileId?: string;
    /** Name of the screenshot file */
    fileName?: string;
    /** Format of the screenshot data */
    format?: Airtop.ScreenshotMetadataFormat;
    /** Scroll position where the screenshot was taken */
    scrollPosition?: Airtop.ScreenshotScrollPosition;
    /** Signed URL for downloading the screenshot (when format is 'url') */
    signedDownloadUrl?: string;
    /** Expiration time for the signed URL in ISO format */
    urlExpiry?: string;
    /** Viewport dimensions of the screenshot */
    viewportDimensions?: Airtop.ScreenshotViewportDimensions;
}
