/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Format of the screenshot data
 */
export type ScreenshotMetadataFormat = "base64" | "url";
export const ScreenshotMetadataFormat = {
    Base64: "base64",
    Url: "url",
} as const;
