/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScrollByConfig {
    /** The amount of pixels/percentage to scroll horizontally. Percentage values should be between 0 and 100. Positive values scroll right, negative values scroll left. */
    xAxis?: string;
    /** The amount of pixels/percentage to scroll vertically. Percentage values should be between 0 and 100. Positive values scroll down, negative values scroll up. */
    yAxis?: string;
}
