/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScrollToEdgeConfig {
    /** Scroll to the left or right of the page. */
    xAxis?: string;
    /** Scroll to the top or bottom of the page. */
    yAxis?: string;
}
