/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionContentPromptResponse {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** The response data from the prompt about the browser window */
    data: Airtop.SessionContentPromptResponseOutput;
    /** Metadata about the response */
    meta: Airtop.SessionAiResponseMetadata;
}
