/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionConfigV1 {
    /** Id of a profile to load into the session. */
    baseProfileId?: string;
    /** - */
    extensionIds?: string[];
    /** Persist the profile. */
    persistProfile?: boolean;
    /** Proxy configuration. */
    proxy?: Airtop.SessionConfigV1Proxy;
    /** Max length of session in minutes, after which it will terminate if not already deleted. */
    timeoutMinutes?: number;
}
