/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

/**
 * Proxy configuration.
 */
export type SessionConfigV1Proxy =
    /**
     * True to use airtop provided proxy */
    | boolean
    /**
     * Configuration for a single custom proxy. */
    | Airtop.CustomProxy
    /**
     * Array of proxy configurations. Includes a domain pattern and a proxy configuration to assign proxies to specific domains. */
    | Airtop.SessionConfigV1ProxyItem[];
