/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionPaginatedExtractionResponse {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** The extracted data and final response from the browser prompt */
    data: Airtop.SessionAiResponseData;
    /** Metadata about the response */
    meta: Airtop.SessionAiResponseMetadata;
}
