/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionAiResponseData {
    /** The response to the prompt about this specific browser window */
    output: string;
    /** outcome of the operation */
    status: Airtop.SessionAiResponseDataStatus;
}
