/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionAiResponse {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** The response data from the prompt about the browser window */
    data: Airtop.SessionAiResponseData;
    /** Any errors that occurred while processing the request */
    errors?: Airtop.SessionAiResponseIssue[];
    /** Metadata about the response */
    meta: Airtop.SessionAiResponseMetadata;
    /** Any warnings that occurred while processing the request */
    warnings?: Airtop.SessionAiResponseIssue[];
}
