/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionAiResponseResponseMetadataModelUsage {
    cost: number;
    credits: number;
    inputTokens: number;
    modelName: string;
    outputTokens: number;
}
