/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionAiResponseMetadataUsage {
    /** The credit usage for this request */
    credits: number;
    /** The total internal cost of this request */
    totalCost: number;
}
