/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SessionConfigV1 {
    /** - */
    extensionConfigurationName?: string;
    /** - */
    extensionIds?: string[];
}
