/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionOutputV1Body {
    /** A URL to the JSON Schema for this object. */
    schema?: string;
    /** Connection info for the session */
    connectionInfo?: Airtop.ConnectionInfo;
    /** Session */
    session: Airtop.Session;
}
