/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionResponse {
    data: Airtop.ExternalSessionWithConnectionInfo;
    errors?: Airtop.Issue[];
    meta: Airtop.EnvelopeDefaultMeta;
    warnings?: Airtop.Issue[];
}
