/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SessionWithConnectionInfoEnvelopeDefaultMetaWrapper {
    data: Airtop.SessionWithConnectionInfo;
    errors?: Airtop.Issue[];
    meta: Airtop.DefaultMetaWrapper;
    warnings?: Airtop.Issue[];
}
