/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface StatusMessage {
    /** Event name */
    event: string;
    /** Date and Time of the event */
    eventTime: Date;
    /** ID of the session */
    id: string;
    /** Status of the session */
    status: Airtop.StatusMessageStatus;
}
