/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface SummaryConfig {
    experimental?: Airtop.SummaryExperimentalConfig;
    /** JSON schema defining the structure of the output. If not provided, the format of the output might vary. */
    outputSchema?: string;
}
