/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VibeCodingConfig {
    /** - */
    agentVersion?: number;
    /** - */
    enabled?: boolean;
    /** - */
    sourceViceS3Id?: number;
}
