/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The direction to partition the screenshot into chunks: 'vertical', 'horizontal', or 'bidirectional'. Defaults to 'vertical', which is recommended for most web pages. For optimal results when partitioning in a single direction, ensure the perpendicular dimension does not exceed 1920 pixels.
 */
export type VisualAnalysisConfigPartitionDirection = "vertical" | "horizontal" | "bidirectional";

export const VisualAnalysisConfigPartitionDirection = {
    Vertical: "vertical",
    Horizontal: "horizontal",
    Bidirectional: "bidirectional",
} as const;
