/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../index";

export interface WindowsWithMeta {
    /** List of windows in the session. */
    windows?: Airtop.WindowId[];
}
