/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Window {
    /** Url for live view session */
    liveViewUrl: string;
    /** Token for authenticating to a live view session */
    token: string;
    /** Window ID for live view session */
    windowId: string;
}
