/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WindowId {
    /** CDP Window target ID */
    targetId: string;
    /** Airtop window ID of the browser window */
    windowId: string;
}
