/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Wait until the specified loading event occurs. Defaults to 'load', which waits until the page has loaded
 */
export type CreateWindowInputV1BodyWaitUntil = "load" | "domContentLoaded";

export const CreateWindowInputV1BodyWaitUntil = {
    Load: "load",
    DomContentLoaded: "domContentLoaded",
} as const;
