/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The target status of the page
 */
export type WaitForPageRequestTargetStatus = "domcontentloaded" | "load";
export const WaitForPageRequestTargetStatus = {
    Domcontentloaded: "domcontentloaded",
    Load: "load",
} as const;
