/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { AiResponseEnvelope } from "./AiResponseEnvelope";
import { Issue } from "./Issue";
import { ExternalSessionAiResponseMetadata } from "./ExternalSessionAiResponseMetadata";

export const AiPromptResponse: core.serialization.ObjectSchema<
    serializers.AiPromptResponse.Raw,
    Airtop.AiPromptResponse
> = core.serialization.object({
    data: AiResponseEnvelope,
    errors: core.serialization.list(Issue).optional(),
    meta: ExternalSessionAiResponseMetadata,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace AiPromptResponse {
    interface Raw {
        data: AiResponseEnvelope.Raw;
        errors?: Issue.Raw[] | null;
        meta: ExternalSessionAiResponseMetadata.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
