/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const AiResponseEnvelope: core.serialization.ObjectSchema<
    serializers.AiResponseEnvelope.Raw,
    Airtop.AiResponseEnvelope
> = core.serialization.object({
    modelResponse: core.serialization.string(),
});

export declare namespace AiResponseEnvelope {
    export interface Raw {
        modelResponse: string;
    }
}
