/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const AutomationOutput: core.serialization.ObjectSchema<
    serializers.AutomationOutput.Raw,
    Airtop.AutomationOutput
> = core.serialization.object({
    description: core.serialization.string().optional(),
    domainName: core.serialization.string(),
    id: core.serialization.string(),
    schema: core.serialization.string().optional(),
    template: core.serialization.string().optional(),
});

export declare namespace AutomationOutput {
    interface Raw {
        description?: string | null;
        domainName: string;
        id: string;
        schema?: string | null;
        template?: string | null;
    }
}
