/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const BrowserWaitSelectorConfig: core.serialization.ObjectSchema<
    serializers.BrowserWaitSelectorConfig.Raw,
    Airtop.BrowserWaitSelectorConfig
> = core.serialization.object({
    hidden: core.serialization.boolean().optional(),
    timeoutSeconds: core.serialization.number().optional(),
    visible: core.serialization.boolean().optional(),
});

export declare namespace BrowserWaitSelectorConfig {
    interface Raw {
        hidden?: boolean | null;
        timeoutSeconds?: number | null;
        visible?: boolean | null;
    }
}
