/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { BrowserWaitNavigationConfigWaitUntil } from "./BrowserWaitNavigationConfigWaitUntil";

export const BrowserWaitNavigationConfig: core.serialization.ObjectSchema<
    serializers.BrowserWaitNavigationConfig.Raw,
    Airtop.BrowserWaitNavigationConfig
> = core.serialization.object({
    timeoutSeconds: core.serialization.number().optional(),
    waitUntil: BrowserWaitNavigationConfigWaitUntil.optional(),
});

export declare namespace BrowserWaitNavigationConfig {
    export interface Raw {
        timeoutSeconds?: number | null;
        waitUntil?: BrowserWaitNavigationConfigWaitUntil.Raw | null;
    }
}
