/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { CaptchaEventMessageStatus } from "./CaptchaEventMessageStatus";

export const CaptchaEventMessage: core.serialization.ObjectSchema<
    serializers.CaptchaEventMessage.Raw,
    Airtop.CaptchaEventMessage
> = core.serialization.object({
    duration: core.serialization.number(),
    event: core.serialization.string(),
    eventTime: core.serialization.date(),
    id: core.serialization.string(),
    retryCount: core.serialization.number(),
    status: CaptchaEventMessageStatus,
    type: core.serialization.string(),
    url: core.serialization.string(),
    windowId: core.serialization.string(),
});

export declare namespace CaptchaEventMessage {
    export interface Raw {
        duration: number;
        event: string;
        eventTime: string;
        id: string;
        retryCount: number;
        status: CaptchaEventMessageStatus.Raw;
        type: string;
        url: string;
        windowId: string;
    }
}
