/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const CaptchaEventMessageStatus: core.serialization.Schema<
    serializers.CaptchaEventMessageStatus.Raw,
    Airtop.CaptchaEventMessageStatus
> = core.serialization.enum_(["processing", "completed", "failed"]);

export declare namespace CaptchaEventMessageStatus {
    export type Raw = "processing" | "completed" | "failed";
}
