/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ScrapeResponseContent } from "./ScrapeResponseContent";

export const CleanScrapeResponseOutput: core.serialization.ObjectSchema<
    serializers.CleanScrapeResponseOutput.Raw,
    Airtop.CleanScrapeResponseOutput
> = core.serialization.object({
    scrapedContent: ScrapeResponseContent,
    selectedText: core.serialization.string(),
    title: core.serialization.string(),
});

export declare namespace CleanScrapeResponseOutput {
    interface Raw {
        scrapedContent: ScrapeResponseContent.Raw;
        selectedText: string;
        title: string;
    }
}
