/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const CleanScrapeResponseDataStatus: core.serialization.Schema<
    serializers.CleanScrapeResponseDataStatus.Raw,
    Airtop.CleanScrapeResponseDataStatus
> = core.serialization.enum_(["success", "partial_success", "failure"]);

export declare namespace CleanScrapeResponseDataStatus {
    type Raw = "success" | "partial_success" | "failure";
}
