/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { CleanScrapeResponseOutput } from "./CleanScrapeResponseOutput";
import { CleanScrapeResponseDataStatus } from "./CleanScrapeResponseDataStatus";

export const CleanScrapeResponseData: core.serialization.ObjectSchema<
    serializers.CleanScrapeResponseData.Raw,
    Airtop.CleanScrapeResponseData
> = core.serialization.object({
    output: CleanScrapeResponseOutput,
    status: CleanScrapeResponseDataStatus,
});

export declare namespace CleanScrapeResponseData {
    interface Raw {
        output: CleanScrapeResponseOutput.Raw;
        status: CleanScrapeResponseDataStatus.Raw;
    }
}
