/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { CleanScrapeResponseData } from "./CleanScrapeResponseData";
import { SessionAiResponseMetadata } from "./SessionAiResponseMetadata";

export const CleanScrapeResponse: core.serialization.ObjectSchema<
    serializers.CleanScrapeResponse.Raw,
    Airtop.CleanScrapeResponse
> = core.serialization.object({
    schema: core.serialization.property("$schema", core.serialization.string().optional()),
    data: CleanScrapeResponseData,
    meta: SessionAiResponseMetadata,
});

export declare namespace CleanScrapeResponse {
    interface Raw {
        $schema?: string | null;
        data: CleanScrapeResponseData.Raw;
        meta: SessionAiResponseMetadata.Raw;
    }
}
