/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { VisualAnalysisConfig } from "./VisualAnalysisConfig";

export const ClickConfig: core.serialization.ObjectSchema<serializers.ClickConfig.Raw, Airtop.ClickConfig> =
    core.serialization.object({
        visualAnalysis: VisualAnalysisConfig.optional(),
    });

export declare namespace ClickConfig {
    interface Raw {
        visualAnalysis?: VisualAnalysisConfig.Raw | null;
    }
}
