/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ClickConfigClickType: core.serialization.Schema<
    serializers.ClickConfigClickType.Raw,
    Airtop.ClickConfigClickType
> = core.serialization.enum_(["click", "doubleClick", "rightClick"]);

export declare namespace ClickConfigClickType {
    type Raw = "click" | "doubleClick" | "rightClick";
}
