/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { LiveViewConnectionInfo } from "./LiveViewConnectionInfo";

export const ConnectionInfo: core.serialization.ObjectSchema<serializers.ConnectionInfo.Raw, Airtop.ConnectionInfo> =
    core.serialization.object({
        cdpUrl: core.serialization.property("cdp_url", core.serialization.string().optional()),
        cdpWsUrl: core.serialization.property("cdp_ws_url", core.serialization.string().optional()),
        chromedriverUrl: core.serialization.property("chromedriver_url", core.serialization.string().optional()),
        liveView: core.serialization.property("live_view", LiveViewConnectionInfo.optional()),
    });

export declare namespace ConnectionInfo {
    interface Raw {
        cdp_url?: string | null;
        cdp_ws_url?: string | null;
        chromedriver_url?: string | null;
        live_view?: LiveViewConnectionInfo.Raw | null;
    }
}
