/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const CreateFileV1FileType: core.serialization.Schema<
    serializers.CreateFileV1FileType.Raw,
    Airtop.CreateFileV1FileType
> = core.serialization.enum_(["browser_download", "screenshot", "video", "customer_upload"]);

export declare namespace CreateFileV1FileType {
    type Raw = "browser_download" | "screenshot" | "video" | "customer_upload";
}
