/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const DefaultMetaWrapper: core.serialization.ObjectSchema<
    serializers.DefaultMetaWrapper.Raw,
    Airtop.DefaultMetaWrapper
> = core.serialization.object({
    requestId: core.serialization.string().optional(),
});

export declare namespace DefaultMetaWrapper {
    interface Raw {
        requestId?: string | null;
    }
}
