/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const DeleteAutomationOutputWrapperBody: core.serialization.Schema<
    serializers.DeleteAutomationOutputWrapperBody.Raw,
    Airtop.DeleteAutomationOutputWrapperBody
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace DeleteAutomationOutputWrapperBody {
    type Raw = Record<string, unknown>;
}
