/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const EmptyResponseJson: core.serialization.ObjectSchema<
    serializers.EmptyResponseJson.Raw,
    Airtop.EmptyResponseJson
> = core.serialization.object({
    success: core.serialization.boolean(),
});

export declare namespace EmptyResponseJson {
    interface Raw {
        success: boolean;
    }
}
