/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ExtensionV1 } from "./ExtensionV1";
import { Issue } from "./Issue";
import { EnvelopeDefaultMeta } from "./EnvelopeDefaultMeta";

export const EnvelopeListExtensionV1EnvelopeDefaultMeta: core.serialization.ObjectSchema<
    serializers.EnvelopeListExtensionV1EnvelopeDefaultMeta.Raw,
    Airtop.EnvelopeListExtensionV1EnvelopeDefaultMeta
> = core.serialization.object({
    data: core.serialization.list(ExtensionV1).optional(),
    errors: core.serialization.list(Issue).optional(),
    meta: EnvelopeDefaultMeta,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace EnvelopeListExtensionV1EnvelopeDefaultMeta {
    interface Raw {
        data?: ExtensionV1.Raw[] | null;
        errors?: Issue.Raw[] | null;
        meta: EnvelopeDefaultMeta.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
