/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ExtensionV1 } from "./ExtensionV1";
import { Issue } from "./Issue";
import { EnvelopeDefaultMeta } from "./EnvelopeDefaultMeta";

export const EnvelopeExtensionV1EnvelopeDefaultMeta: core.serialization.ObjectSchema<
    serializers.EnvelopeExtensionV1EnvelopeDefaultMeta.Raw,
    Airtop.EnvelopeExtensionV1EnvelopeDefaultMeta
> = core.serialization.object({
    data: ExtensionV1,
    errors: core.serialization.list(Issue).optional(),
    meta: EnvelopeDefaultMeta,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace EnvelopeExtensionV1EnvelopeDefaultMeta {
    interface Raw {
        data: ExtensionV1.Raw;
        errors?: Issue.Raw[] | null;
        meta: EnvelopeDefaultMeta.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
