/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { GetFileV1 } from "./GetFileV1";
import { Issue } from "./Issue";
import { EnvelopeDefaultMeta } from "./EnvelopeDefaultMeta";

export const EnvelopeGetFileV1EnvelopeDefaultMeta: core.serialization.ObjectSchema<
    serializers.EnvelopeGetFileV1EnvelopeDefaultMeta.Raw,
    Airtop.EnvelopeGetFileV1EnvelopeDefaultMeta
> = core.serialization.object({
    data: GetFileV1,
    errors: core.serialization.list(Issue).optional(),
    meta: EnvelopeDefaultMeta,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace EnvelopeGetFileV1EnvelopeDefaultMeta {
    interface Raw {
        data: GetFileV1.Raw;
        errors?: Issue.Raw[] | null;
        meta: EnvelopeDefaultMeta.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
