/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ErrorMessage: core.serialization.ObjectSchema<serializers.ErrorMessage.Raw, Airtop.ErrorMessage> =
    core.serialization.object({
        code: core.serialization.string(),
        event: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace ErrorMessage {
    interface Raw {
        code: string;
        event: string;
        message: string;
    }
}
