/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ExtensionConfigurationOutput: core.serialization.ObjectSchema<
    serializers.ExtensionConfigurationOutput.Raw,
    Airtop.ExtensionConfigurationOutput
> = core.serialization.object({
    createdAt: core.serialization.date().optional(),
    extensionIds: core.serialization.list(core.serialization.string()).optional(),
    name: core.serialization.string(),
    updatedAt: core.serialization.date().optional(),
});

export declare namespace ExtensionConfigurationOutput {
    interface Raw {
        createdAt?: string | null;
        extensionIds?: string[] | null;
        name: string;
        updatedAt?: string | null;
    }
}
