/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ExternalProfileV1: core.serialization.ObjectSchema<
    serializers.ExternalProfileV1.Raw,
    Airtop.ExternalProfileV1
> = core.serialization.object({
    profileId: core.serialization.string(),
    status: core.serialization.string().optional(),
});

export declare namespace ExternalProfileV1 {
    interface Raw {
        profileId: string;
        status?: string | null;
    }
}
