/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ExternalFile: core.serialization.ObjectSchema<serializers.ExternalFile.Raw, Airtop.ExternalFile> =
    core.serialization.object({
        deleted: core.serialization.boolean(),
        deletionTime: core.serialization.date().optional(),
        fileBytes: core.serialization.number(),
        fileName: core.serialization.string(),
        fileType: core.serialization.string(),
        id: core.serialization.string(),
        lastHeartbeatTime: core.serialization.date().optional(),
        orgId: core.serialization.string(),
        sessionId: core.serialization.string().optional(),
        status: core.serialization.string(),
        uploadedCompleteTime: core.serialization.date().optional(),
        uploadedStartTime: core.serialization.date(),
        visibleInApi: core.serialization.boolean(),
        visibleInPortal: core.serialization.boolean(),
    });

export declare namespace ExternalFile {
    interface Raw {
        deleted: boolean;
        deletionTime?: string | null;
        fileBytes: number;
        fileName: string;
        fileType: string;
        id: string;
        lastHeartbeatTime?: string | null;
        orgId: string;
        sessionId?: string | null;
        status: string;
        uploadedCompleteTime?: string | null;
        uploadedStartTime: string;
        visibleInApi: boolean;
        visibleInPortal: boolean;
    }
}
