/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ExternalSessionAiResponseMetadataUsage: core.serialization.ObjectSchema<
    serializers.ExternalSessionAiResponseMetadataUsage.Raw,
    Airtop.ExternalSessionAiResponseMetadataUsage
> = core.serialization.object({
    credits: core.serialization.number(),
    id: core.serialization.string(),
});

export declare namespace ExternalSessionAiResponseMetadataUsage {
    interface Raw {
        credits: number;
        id: string;
    }
}
