/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ExternalFile } from "./ExternalFile";
import { Pagination } from "./Pagination";

export const FilesWithPagination: core.serialization.ObjectSchema<
    serializers.FilesWithPagination.Raw,
    Airtop.FilesWithPagination
> = core.serialization.object({
    files: core.serialization.list(ExternalFile).optional(),
    pagination: Pagination,
});

export declare namespace FilesWithPagination {
    interface Raw {
        files?: ExternalFile.Raw[] | null;
        pagination: Pagination.Raw;
    }
}
