/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const FileEventData: core.serialization.ObjectSchema<serializers.FileEventData.Raw, Airtop.FileEventData> =
    core.serialization.object({
        error: core.serialization.string(),
        filePath: core.serialization.string(),
    });

export declare namespace FileEventData {
    export interface Raw {
        error: string;
        filePath: string;
    }
}
