/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const FileEventMessageStatus: core.serialization.Schema<
    serializers.FileEventMessageStatus.Raw,
    Airtop.FileEventMessageStatus
> = core.serialization.enum_(["available", "uploading", "upload_failed", "deleted"]);

export declare namespace FileEventMessageStatus {
    export type Raw = "available" | "uploading" | "upload_failed" | "deleted";
}
