/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { FileEventMessageStatus } from "./FileEventMessageStatus";

export const FileEventMessage: core.serialization.ObjectSchema<
    serializers.FileEventMessage.Raw,
    Airtop.FileEventMessage
> = core.serialization.object({
    downloadUrl: core.serialization.string(),
    event: core.serialization.string(),
    eventTime: core.serialization.date(),
    fileId: core.serialization.string(),
    status: FileEventMessageStatus,
});

export declare namespace FileEventMessage {
    export interface Raw {
        downloadUrl: string;
        event: string;
        eventTime: string;
        fileId: string;
        status: FileEventMessageStatus.Raw;
    }
}
