/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { GetFileV1FileType } from "./GetFileV1FileType";
import { GetFileV1Status } from "./GetFileV1Status";

export const GetFileV1: core.serialization.ObjectSchema<serializers.GetFileV1.Raw, Airtop.GetFileV1> =
    core.serialization.object({
        downloadUrl: core.serialization.string(),
        expiryTime: core.serialization.date().optional(),
        fileBytes: core.serialization.number(),
        fileName: core.serialization.string(),
        fileType: GetFileV1FileType,
        id: core.serialization.string(),
        orgId: core.serialization.string(),
        sessionIds: core.serialization.list(core.serialization.string()).optional(),
        status: GetFileV1Status,
        uploadStartTime: core.serialization.date(),
    });

export declare namespace GetFileV1 {
    export interface Raw {
        downloadUrl: string;
        expiryTime?: string | null;
        fileBytes: number;
        fileName: string;
        fileType: GetFileV1FileType.Raw;
        id: string;
        orgId: string;
        sessionIds?: string[] | null;
        status: GetFileV1Status.Raw;
        uploadStartTime: string;
    }
}
