/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { GetFileV1FileType } from "./GetFileV1FileType";

export const GetFileV1: core.serialization.ObjectSchema<serializers.GetFileV1.Raw, Airtop.GetFileV1> =
    core.serialization.object({
        downloadUrl: core.serialization.string(),
        fileBytes: core.serialization.number(),
        fileName: core.serialization.string(),
        fileType: GetFileV1FileType,
        id: core.serialization.string(),
        orgId: core.serialization.string(),
        sessionId: core.serialization.string().optional(),
        uploadedAt: core.serialization.date(),
    });

export declare namespace GetFileV1 {
    interface Raw {
        downloadUrl: string;
        fileBytes: number;
        fileName: string;
        fileType: GetFileV1FileType.Raw;
        id: string;
        orgId: string;
        sessionId?: string | null;
        uploadedAt: string;
    }
}
