/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const IntervalMonitorConfig: core.serialization.ObjectSchema<
    serializers.IntervalMonitorConfig.Raw,
    Airtop.IntervalMonitorConfig
> = core.serialization.object({
    intervalSeconds: core.serialization.number().optional(),
    timeoutSeconds: core.serialization.number().optional(),
});

export declare namespace IntervalMonitorConfig {
    interface Raw {
        intervalSeconds?: number | null;
        timeoutSeconds?: number | null;
    }
}
