/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const Issue: core.serialization.ObjectSchema<serializers.Issue.Raw, Airtop.Issue> = core.serialization.object({
    code: core.serialization.string().optional(),
    details: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    message: core.serialization.string(),
    reason: core.serialization.string().optional(),
});

export declare namespace Issue {
    interface Raw {
        code?: string | null;
        details?: Record<string, unknown> | null;
        message: string;
        reason?: string | null;
    }
}
