/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { AutomationOutput } from "./AutomationOutput";

export const ListAutomationsOutput: core.serialization.ObjectSchema<
    serializers.ListAutomationsOutput.Raw,
    Airtop.ListAutomationsOutput
> = core.serialization.object({
    automations: core.serialization.list(AutomationOutput).optional(),
});

export declare namespace ListAutomationsOutput {
    export interface Raw {
        automations?: AutomationOutput.Raw[] | null;
    }
}
