/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const MicroInteractionExperimentalConfig: core.serialization.ObjectSchema<
    serializers.MicroInteractionExperimentalConfig.Raw,
    Airtop.MicroInteractionExperimentalConfig
> = core.serialization.object({
    scrollWithin: core.serialization.string().optional(),
});

export declare namespace MicroInteractionExperimentalConfig {
    interface Raw {
        scrollWithin?: string | null;
    }
}
