/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ModelResponse: core.serialization.ObjectSchema<serializers.ModelResponse.Raw, Airtop.ModelResponse> =
    core.serialization.object({
        modelResponse: core.serialization.string(),
    });

export declare namespace ModelResponse {
    interface Raw {
        modelResponse: string;
    }
}
