/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const MonitorConfigMonitorType: core.serialization.Schema<
    serializers.MonitorConfigMonitorType.Raw,
    Airtop.MonitorConfigMonitorType
> = core.serialization.enum_(["interval", "selector"]);

export declare namespace MonitorConfigMonitorType {
    type Raw = "interval" | "selector";
}
