/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const OperationOutcome: core.serialization.ObjectSchema<
    serializers.OperationOutcome.Raw,
    Airtop.OperationOutcome
> = core.serialization.object({
    success: core.serialization.boolean(),
});

export declare namespace OperationOutcome {
    export interface Raw {
        success: boolean;
    }
}
