/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const Pagination: core.serialization.ObjectSchema<serializers.Pagination.Raw, Airtop.Pagination> =
    core.serialization.object({
        currentLimit: core.serialization.number(),
        currentPage: core.serialization.number(),
        finalCount: core.serialization.number(),
        hasMore: core.serialization.boolean(),
        initialCount: core.serialization.number(),
        nextOffset: core.serialization.number(),
        numberOfPages: core.serialization.number(),
        totalItems: core.serialization.number(),
    });

export declare namespace Pagination {
    export interface Raw {
        currentLimit: number;
        currentPage: number;
        finalCount: number;
        hasMore: boolean;
        initialCount: number;
        nextOffset: number;
        numberOfPages: number;
        totalItems: number;
    }
}
