/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { PaginatedExtractionExperimentalConfig } from "./PaginatedExtractionExperimentalConfig";
import { ScrapeConfig } from "./ScrapeConfig";

export const PaginatedExtractionConfig: core.serialization.ObjectSchema<
    serializers.PaginatedExtractionConfig.Raw,
    Airtop.PaginatedExtractionConfig
> = core.serialization.object({
    experimental: PaginatedExtractionExperimentalConfig.optional(),
    interactionMode: core.serialization.string().optional(),
    outputSchema: core.serialization.string().optional(),
    paginationMode: core.serialization.string().optional(),
    scrape: ScrapeConfig.optional(),
});

export declare namespace PaginatedExtractionConfig {
    export interface Raw {
        experimental?: PaginatedExtractionExperimentalConfig.Raw | null;
        interactionMode?: string | null;
        outputSchema?: string | null;
        paginationMode?: string | null;
        scrape?: ScrapeConfig.Raw | null;
    }
}
