/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const PromptContentExperimentalConfig: core.serialization.ObjectSchema<
    serializers.PromptContentExperimentalConfig.Raw,
    Airtop.PromptContentExperimentalConfig
> = core.serialization.object({
    includeVisualAnalysis: core.serialization.string().optional(),
});

export declare namespace PromptContentExperimentalConfig {
    interface Raw {
        includeVisualAnalysis?: string | null;
    }
}
