/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ProxyCredentials: core.serialization.ObjectSchema<
    serializers.ProxyCredentials.Raw,
    Airtop.ProxyCredentials
> = core.serialization.object({
    password: core.serialization.string().optional(),
    url: core.serialization.string(),
    username: core.serialization.string().optional(),
});

export declare namespace ProxyCredentials {
    interface Raw {
        password?: string | null;
        url: string;
        username?: string | null;
    }
}
