/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { AirtopProxyConfiguration } from "./AirtopProxyConfiguration";
import { ProxyCredentials } from "./ProxyCredentials";

export const Proxy: core.serialization.Schema<serializers.Proxy.Raw, Airtop.Proxy> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), AirtopProxyConfiguration, ProxyCredentials]);

export declare namespace Proxy {
    type Raw = string | AirtopProxyConfiguration.Raw | ProxyCredentials.Raw;
}
