/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const RequestStatusResponse: core.serialization.ObjectSchema<
    serializers.RequestStatusResponse.Raw,
    Airtop.RequestStatusResponse
> = core.serialization.object({
    response: core.serialization.unknown(),
    status: core.serialization.string(),
});

export declare namespace RequestStatusResponse {
    interface Raw {
        response?: unknown;
        status: string;
    }
}
