/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScrapeResponseContent: core.serialization.ObjectSchema<
    serializers.ScrapeResponseContent.Raw,
    Airtop.ScrapeResponseContent
> = core.serialization.object({
    contentType: core.serialization.string(),
    text: core.serialization.string(),
});

export declare namespace ScrapeResponseContent {
    export interface Raw {
        contentType: string;
        text: string;
    }
}
