/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScrapeConfig: core.serialization.ObjectSchema<serializers.ScrapeConfig.Raw, Airtop.ScrapeConfig> =
    core.serialization.object({
        optimizeUrls: core.serialization.string().optional(),
    });

export declare namespace ScrapeConfig {
    export interface Raw {
        optimizeUrls?: string | null;
    }
}
