/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ScrapeResponseOutput } from "./ScrapeResponseOutput";

export const ScrapeResponseEnvelope: core.serialization.ObjectSchema<
    serializers.ScrapeResponseEnvelope.Raw,
    Airtop.ScrapeResponseEnvelope
> = core.serialization.object({
    modelResponse: ScrapeResponseOutput,
});

export declare namespace ScrapeResponseEnvelope {
    interface Raw {
        modelResponse: ScrapeResponseOutput.Raw;
    }
}
