/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ScrapeModelResponse } from "./ScrapeModelResponse";
import { Issue } from "./Issue";
import { ExternalSessionAiResponseMetadata } from "./ExternalSessionAiResponseMetadata";

export const ScrapeModelResponseExternalSessionAiResponseMetadataWrapper: core.serialization.ObjectSchema<
    serializers.ScrapeModelResponseExternalSessionAiResponseMetadataWrapper.Raw,
    Airtop.ScrapeModelResponseExternalSessionAiResponseMetadataWrapper
> = core.serialization.object({
    data: ScrapeModelResponse,
    errors: core.serialization.list(Issue).optional(),
    meta: ExternalSessionAiResponseMetadata,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace ScrapeModelResponseExternalSessionAiResponseMetadataWrapper {
    interface Raw {
        data: ScrapeModelResponse.Raw;
        errors?: Issue.Raw[] | null;
        meta: ExternalSessionAiResponseMetadata.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
