/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScreenshotViewportDimensions: core.serialization.ObjectSchema<
    serializers.ScreenshotViewportDimensions.Raw,
    Airtop.ScreenshotViewportDimensions
> = core.serialization.object({
    height: core.serialization.number(),
    width: core.serialization.number(),
});

export declare namespace ScreenshotViewportDimensions {
    export interface Raw {
        height: number;
        width: number;
    }
}
