/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScreenshotConfig: core.serialization.ObjectSchema<
    serializers.ScreenshotConfig.Raw,
    Airtop.ScreenshotConfig
> = core.serialization.object({
    maxHeight: core.serialization.number().optional(),
    maxWidth: core.serialization.number().optional(),
    quality: core.serialization.number().optional(),
    scope: core.serialization.stringLiteral("viewport").optional(),
});

export declare namespace ScreenshotConfig {
    export interface Raw {
        maxHeight?: number | null;
        maxWidth?: number | null;
        quality?: number | null;
        scope?: "viewport" | null;
    }
}
