/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScreenshotMetadataFormat: core.serialization.Schema<
    serializers.ScreenshotMetadataFormat.Raw,
    Airtop.ScreenshotMetadataFormat
> = core.serialization.enum_(["base64", "url"]);

export declare namespace ScreenshotMetadataFormat {
    export type Raw = "base64" | "url";
}
