/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScreenshotConfigScope: core.serialization.Schema<
    serializers.ScreenshotConfigScope.Raw,
    Airtop.ScreenshotConfigScope
> = core.serialization.enum_(["viewport", "page", "scan", "auto"]);

export declare namespace ScreenshotConfigScope {
    export type Raw = "viewport" | "page" | "scan" | "auto";
}
