/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScreenshotScrollPosition: core.serialization.ObjectSchema<
    serializers.ScreenshotScrollPosition.Raw,
    Airtop.ScreenshotScrollPosition
> = core.serialization.object({
    left: core.serialization.number(),
    top: core.serialization.number(),
});

export declare namespace ScreenshotScrollPosition {
    export interface Raw {
        left: number;
        top: number;
    }
}
