/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const ScrollToEdgeConfig: core.serialization.ObjectSchema<
    serializers.ScrollToEdgeConfig.Raw,
    Airtop.ScrollToEdgeConfig
> = core.serialization.object({
    xAxis: core.serialization.string().optional(),
    yAxis: core.serialization.string().optional(),
});

export declare namespace ScrollToEdgeConfig {
    interface Raw {
        xAxis?: string | null;
        yAxis?: string | null;
    }
}
