/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const SessionConfigV1: core.serialization.ObjectSchema<serializers.SessionConfigV1.Raw, Airtop.SessionConfigV1> =
    core.serialization.object({
        extensionConfigurationName: core.serialization.string().optional(),
        extensionIds: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace SessionConfigV1 {
    interface Raw {
        extensionConfigurationName?: string | null;
        extensionIds?: string[] | null;
    }
}
