/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { CustomProxy } from "./CustomProxy";

export const SessionConfigV1ProxyItem: core.serialization.ObjectSchema<
    serializers.SessionConfigV1ProxyItem.Raw,
    Airtop.SessionConfigV1ProxyItem
> = core.serialization.object({
    domainPattern: core.serialization.string(),
    relay: CustomProxy,
});

export declare namespace SessionConfigV1ProxyItem {
    interface Raw {
        domainPattern: string;
        relay: CustomProxy.Raw;
    }
}
