/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { Pagination } from "./Pagination";
import { ExternalSessionWithConnectionInfo } from "./ExternalSessionWithConnectionInfo";

export const SessionsWithPagination: core.serialization.ObjectSchema<
    serializers.SessionsWithPagination.Raw,
    Airtop.SessionsWithPagination
> = core.serialization.object({
    pagination: Pagination,
    sessions: core.serialization.list(ExternalSessionWithConnectionInfo).optional(),
});

export declare namespace SessionsWithPagination {
    export interface Raw {
        pagination: Pagination.Raw;
        sessions?: ExternalSessionWithConnectionInfo.Raw[] | null;
    }
}
