/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionSummaryResponseOutput } from "./SessionSummaryResponseOutput";
import { SessionAiResponseMetadata } from "./SessionAiResponseMetadata";

export const SessionSummaryResponse: core.serialization.ObjectSchema<
    serializers.SessionSummaryResponse.Raw,
    Airtop.SessionSummaryResponse
> = core.serialization.object({
    schema: core.serialization.property("$schema", core.serialization.string().optional()),
    data: SessionSummaryResponseOutput,
    meta: SessionAiResponseMetadata,
});

export declare namespace SessionSummaryResponse {
    interface Raw {
        $schema?: string | null;
        data: SessionSummaryResponseOutput.Raw;
        meta: SessionAiResponseMetadata.Raw;
    }
}
