/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionAiResponseMetadataUsage } from "./SessionAiResponseMetadataUsage";

export const SessionAiResponseMetadata: core.serialization.ObjectSchema<
    serializers.SessionAiResponseMetadata.Raw,
    Airtop.SessionAiResponseMetadata
> = core.serialization.object({
    usage: SessionAiResponseMetadataUsage,
});

export declare namespace SessionAiResponseMetadata {
    interface Raw {
        usage: SessionAiResponseMetadataUsage.Raw;
    }
}
