/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { CustomProxy } from "./CustomProxy";
import { SessionConfigV1ProxyItem } from "./SessionConfigV1ProxyItem";

export const SessionConfigV1Proxy: core.serialization.Schema<
    serializers.SessionConfigV1Proxy.Raw,
    Airtop.SessionConfigV1Proxy
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    CustomProxy,
    core.serialization.list(SessionConfigV1ProxyItem),
]);

export declare namespace SessionConfigV1Proxy {
    type Raw = boolean | CustomProxy.Raw | SessionConfigV1ProxyItem.Raw[];
}
