/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionsWithPagination } from "./SessionsWithPagination";
import { Issue } from "./Issue";
import { EnvelopeDefaultMeta } from "./EnvelopeDefaultMeta";

export const SessionsResponse: core.serialization.ObjectSchema<
    serializers.SessionsResponse.Raw,
    Airtop.SessionsResponse
> = core.serialization.object({
    data: SessionsWithPagination,
    errors: core.serialization.list(Issue).optional(),
    meta: EnvelopeDefaultMeta,
    warnings: core.serialization.list(Issue).optional(),
});

export declare namespace SessionsResponse {
    export interface Raw {
        data: SessionsWithPagination.Raw;
        errors?: Issue.Raw[] | null;
        meta: EnvelopeDefaultMeta.Raw;
        warnings?: Issue.Raw[] | null;
    }
}
