/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionAiResponseData } from "./SessionAiResponseData";
import { SessionAiResponseMetadata } from "./SessionAiResponseMetadata";

export const SessionPaginatedExtractionResponse: core.serialization.ObjectSchema<
    serializers.SessionPaginatedExtractionResponse.Raw,
    Airtop.SessionPaginatedExtractionResponse
> = core.serialization.object({
    schema: core.serialization.property("$schema", core.serialization.string().optional()),
    data: SessionAiResponseData,
    meta: SessionAiResponseMetadata,
});

export declare namespace SessionPaginatedExtractionResponse {
    interface Raw {
        $schema?: string | null;
        data: SessionAiResponseData.Raw;
        meta: SessionAiResponseMetadata.Raw;
    }
}
