/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const SessionConfigV1: core.serialization.ObjectSchema<serializers.SessionConfigV1.Raw, Airtop.SessionConfigV1> =
    core.serialization.object({
        persistProfile: core.serialization.boolean().optional(),
        profileId: core.serialization.string().optional(),
        timeoutMinutes: core.serialization.number().optional(),
    });

export declare namespace SessionConfigV1 {
    interface Raw {
        persistProfile?: boolean | null;
        profileId?: string | null;
        timeoutMinutes?: number | null;
    }
}
