/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const SessionAiResponseResponseMetadataModelUsage: core.serialization.ObjectSchema<
    serializers.SessionAiResponseResponseMetadataModelUsage.Raw,
    Airtop.SessionAiResponseResponseMetadataModelUsage
> = core.serialization.object({
    cost: core.serialization.number(),
    credits: core.serialization.number(),
    inputTokens: core.serialization.number(),
    modelName: core.serialization.string(),
    outputTokens: core.serialization.number(),
});

export declare namespace SessionAiResponseResponseMetadataModelUsage {
    interface Raw {
        cost: number;
        credits: number;
        inputTokens: number;
        modelName: string;
        outputTokens: number;
    }
}
