/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { ConnectionInfo } from "./ConnectionInfo";
import { Session } from "./Session";

export const SessionOutputV1Body: core.serialization.ObjectSchema<
    serializers.SessionOutputV1Body.Raw,
    Airtop.SessionOutputV1Body
> = core.serialization.object({
    schema: core.serialization.property("$schema", core.serialization.string().optional()),
    connectionInfo: core.serialization.property("connection_info", ConnectionInfo.optional()),
    session: Session,
});

export declare namespace SessionOutputV1Body {
    interface Raw {
        $schema?: string | null;
        connection_info?: ConnectionInfo.Raw | null;
        session: Session.Raw;
    }
}
