/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionContentPromptResponseOutput } from "./SessionContentPromptResponseOutput";
import { SessionAiResponseMetadata } from "./SessionAiResponseMetadata";

export const SessionContentPromptResponse: core.serialization.ObjectSchema<
    serializers.SessionContentPromptResponse.Raw,
    Airtop.SessionContentPromptResponse
> = core.serialization.object({
    schema: core.serialization.property("$schema", core.serialization.string().optional()),
    data: SessionContentPromptResponseOutput,
    meta: SessionAiResponseMetadata,
});

export declare namespace SessionContentPromptResponse {
    interface Raw {
        $schema?: string | null;
        data: SessionContentPromptResponseOutput.Raw;
        meta: SessionAiResponseMetadata.Raw;
    }
}
