/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { SessionAiResponseDataStatus } from "./SessionAiResponseDataStatus";

export const SessionAiResponseData: core.serialization.ObjectSchema<
    serializers.SessionAiResponseData.Raw,
    Airtop.SessionAiResponseData
> = core.serialization.object({
    output: core.serialization.string(),
    status: SessionAiResponseDataStatus,
});

export declare namespace SessionAiResponseData {
    interface Raw {
        output: string;
        status: SessionAiResponseDataStatus.Raw;
    }
}
