/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { StatusMessageStatus } from "./StatusMessageStatus";

export const StatusMessage: core.serialization.ObjectSchema<serializers.StatusMessage.Raw, Airtop.StatusMessage> =
    core.serialization.object({
        event: core.serialization.string(),
        eventTime: core.serialization.date(),
        id: core.serialization.string(),
        status: StatusMessageStatus,
    });

export declare namespace StatusMessage {
    interface Raw {
        event: string;
        eventTime: string;
        id: string;
        status: StatusMessageStatus.Raw;
    }
}
