/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";

export const VisualAnalysisConfigResultSelectionStrategy: core.serialization.Schema<
    serializers.VisualAnalysisConfigResultSelectionStrategy.Raw,
    Airtop.VisualAnalysisConfigResultSelectionStrategy
> = core.serialization.enum_(["first", "bestMatch", "auto"]);

export declare namespace VisualAnalysisConfigResultSelectionStrategy {
    type Raw = "first" | "bestMatch" | "auto";
}
