/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { VisualAnalysisConfigPartitionDirection } from "./VisualAnalysisConfigPartitionDirection";
import { VisualAnalysisConfigScope } from "./VisualAnalysisConfigScope";

export const VisualAnalysisConfig: core.serialization.ObjectSchema<
    serializers.VisualAnalysisConfig.Raw,
    Airtop.VisualAnalysisConfig
> = core.serialization.object({
    overlapPercentage: core.serialization.number().optional(),
    partitionDirection: VisualAnalysisConfigPartitionDirection.optional(),
    scope: VisualAnalysisConfigScope.optional(),
});

export declare namespace VisualAnalysisConfig {
    interface Raw {
        overlapPercentage?: number | null;
        partitionDirection?: VisualAnalysisConfigPartitionDirection.Raw | null;
        scope?: VisualAnalysisConfigScope.Raw | null;
    }
}
