/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Airtop from "../../api/index";
import * as core from "../../core";
import { WindowId } from "./WindowId";

export const WindowsWithMeta: core.serialization.ObjectSchema<serializers.WindowsWithMeta.Raw, Airtop.WindowsWithMeta> =
    core.serialization.object({
        windows: core.serialization.list(WindowId).optional(),
    });

export declare namespace WindowsWithMeta {
    export interface Raw {
        windows?: WindowId.Raw[] | null;
    }
}
