/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SessionSummaryHandlerRequestBody {
    clientRequestId?: string;
    /** A credit threshold that, once exceeded, will cause the operation to be cancelled. Note that this is *not* a hard limit, but a threshold that is checked periodically during the course of fulfilling the request. A default threshold is used if not specified, but you can use this option to increase or decrease as needed. Set to 0 to disable this feature entirely (not recommended). */
    costThresholdCredits?: number;
    /** An optional prompt providing the Airtop AI model with additional direction or constraints about the summary (such as desired length). */
    prompt?: string;
    /**
     * A time threshold in seconds that, once exceeded, will cause the operation to be cancelled. Note that this is *not* a hard limit, but a threshold that is checked periodically during the course of fulfilling the request. A default threshold is used if not specified, but you can use this option to increase or decrease as needed. Set to 0 to disable this feature entirely (not recommended).
     *
     * This setting does not extend the maximum session duration provided at the time of session creation.
     */
    timeThresholdSeconds?: number;
}
