/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SummarizeContentRequest {
    clientRequestId?: string;
    costThresholdCredits?: number;
    /** The prompt to submit about the content in the browser window */
    prompt?: string;
    timeThresholdSeconds?: number;
}
