/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../../../../index";

/**
 * @example
 *     {
 *         url: "https://www.airtop.ai"
 *     }
 */
export interface WindowLoadUrlV1Body {
    /** Url to navigate to */
    url: string;
    /** Wait until the specified loading event occurs. Defaults to 'load', which waits until the page dom and it's assets have loaded. 'domContentLoaded' will wait until the dom has loaded, 'complete' will wait until the page and all it's iframes have loaded it's dom and assets. 'noWait' will not wait for any loading event and will return immediately. */
    waitUntil?: Airtop.WindowLoadUrlV1BodyWaitUntil;
    /** Maximum time in seconds to wait for the specified loading event to occur. If the timeout is reached, the operation will still succeed but return a warning indicating the page may still be loading resources. */
    waitUntilTimeoutSeconds?: number;
}
