/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ExtensionConfigurationDeleteRequest {
    /**
     * A comma-separated list of extension configuration names.
     */
    extensionConfigurationNames?: string | string[];
}
