/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";

export const SessionsListRequestStatus: core.serialization.Schema<
    serializers.SessionsListRequestStatus.Raw,
    Airtop.SessionsListRequestStatus
> = core.serialization.enum_(["awaiting_capacity", "initializing", "running", "ended"]);

export declare namespace SessionsListRequestStatus {
    type Raw = "awaiting_capacity" | "initializing" | "running" | "ended";
}
