/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";

export const SessionsListRequestStatus: core.serialization.Schema<
    serializers.SessionsListRequestStatus.Raw,
    Airtop.SessionsListRequestStatus
> = core.serialization.enum_(["awaitingCapacity", "initializing", "running", "ended", "completed", "cancelled", "all"]);

export declare namespace SessionsListRequestStatus {
    export type Raw = "awaitingCapacity" | "initializing" | "running" | "ended" | "completed" | "cancelled" | "all";
}
