/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";
import { WindowEventMessage } from "../../../types/WindowEventMessage";

export const SessionsEventsResponseWindowEvent: core.serialization.ObjectSchema<
    serializers.SessionsEventsResponseWindowEvent.Raw,
    Airtop.SessionsEventsResponseWindowEvent
> = core.serialization.object({
    data: WindowEventMessage,
    id: core.serialization.number().optional(),
    retry: core.serialization.number().optional(),
});

export declare namespace SessionsEventsResponseWindowEvent {
    interface Raw {
        data: WindowEventMessage.Raw;
        id?: number | null;
        retry?: number | null;
    }
}
