/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";
import { FileEventMessage } from "../../../types/FileEventMessage";

export const SessionsEventsResponseFileEvent: core.serialization.ObjectSchema<
    serializers.SessionsEventsResponseFileEvent.Raw,
    Airtop.SessionsEventsResponseFileEvent
> = core.serialization.object({
    data: FileEventMessage,
    id: core.serialization.number().optional(),
    retry: core.serialization.number().optional(),
});

export declare namespace SessionsEventsResponseFileEvent {
    export interface Raw {
        data: FileEventMessage.Raw;
        id?: number | null;
        retry?: number | null;
    }
}
