/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AirtopEnvironment = {
    Default: "https://api.airtop.ai/api",
} as const;

export type AirtopEnvironment = typeof AirtopEnvironment.Default;
