/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";

export const CreateWindowInputV1BodyWaitUntil: core.serialization.Schema<
    serializers.CreateWindowInputV1BodyWaitUntil.Raw,
    Airtop.CreateWindowInputV1BodyWaitUntil
> = core.serialization.enum_(["load", "domContentLoaded", "complete", "noWait"]);

export declare namespace CreateWindowInputV1BodyWaitUntil {
    export type Raw = "load" | "domContentLoaded" | "complete" | "noWait";
}
