/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Airtop from "../../../../api/index";
import * as core from "../../../../core";

export const WaitForPageRequestTargetStatus: core.serialization.Schema<
    serializers.WaitForPageRequestTargetStatus.Raw,
    Airtop.WaitForPageRequestTargetStatus
> = core.serialization.enum_(["domcontentloaded", "load"]);

export declare namespace WaitForPageRequestTargetStatus {
    export type Raw = "domcontentloaded" | "load";
}
