/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Airtop from "../../../index";

export interface SessionsEventsResponseFileEvent {
    data: Airtop.FileEventMessage;
    /** The event ID. */
    id?: number;
    /** The retry time in milliseconds. */
    retry?: number;
}
