/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * status of the session to get
 */
export type SessionsListRequestStatus = "awaiting_capacity" | "initializing" | "running" | "ended";

export const SessionsListRequestStatus = {
    AwaitingCapacity: "awaiting_capacity",
    Initializing: "initializing",
    Running: "running",
    Ended: "ended",
} as const;
