/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the session to get.
 */
export type SessionsListRequestStatus =
    | "awaitingCapacity"
    | "initializing"
    | "running"
    | "ended"
    | "completed"
    | "cancelled"
    | "all";

export const SessionsListRequestStatus = {
    AwaitingCapacity: "awaitingCapacity",
    Initializing: "initializing",
    Running: "running",
    Ended: "ended",
    Completed: "completed",
    Cancelled: "cancelled",
    All: "all",
} as const;
