name: beta tag

on:
  workflow_dispatch: {}

jobs:
  beta-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{secrets.COMMIT_KEY}}"
          ref: beta
        
      - name: tag
        run: |
          AIRTOP_VERSION=$(jq -r .version package.json)
          echo "AIRTOP_VERSION: $AIRTOP_VERSION"
          git tag "$AIRTOP_VERSION" 
          git push origin "$AIRTOP_VERSION"
          gh release create "$AIRTOP_VERSION" --prerelease --latest=false --target beta --notes "Beta release $AIRTOP_VERSION" -t "$AIRTOP_VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
