/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Airtop from "../../../../../api/index";
import * as core from "../../../../../core";

export const ExtensionsPostRequest: core.serialization.Schema<
    serializers.ExtensionsPostRequest.Raw,
    Airtop.ExtensionsPostRequest
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace ExtensionsPostRequest {
    interface Raw {
        name: string;
    }
}
